DevD.FutureMaterials/Models/Produto.cs
using System.ComponentModel.DataAnnotations;

namespace DevD.FutureMaterials.Models
{
    public class Produto
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Nome Obrigatório!"),
         MaxLength(50, ErrorMessage = "Máximo de 50 caracteres!"),
         MinLength(3, ErrorMessage = "Mínimo de 3 caracteres!"),
         Display(Name = "Nome:")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "Nome Obrigatório!"),
         MaxLength(50, ErrorMessage = "Máximo de 50 caracteres!"),
         MinLength(3, ErrorMessage = "Mínimo de 3 caracteres!"),
         Display(Name = "Características:")]
        public string? Caracteristica { get; set; }

        [Display(Name = "Preço Médio:")]
        public double PrecoMedio { get; set; }

        [MaxLength(50, ErrorMessage = "Máximo de 50 caracteres!"),
         Display(Name = "Logotipo:")]
        public string? Logotipo { get; set; }

        [Display(Name = "Ativo:")]
        public bool Ativo { get; set; }

        public TipoProduto? Tipo { get; set; }
    }
}

DevD.FutureMaterials/Controllers/ProdutoController.cs
using DevD.FutureMaterials.Controllers.Filters;
using DevD.FutureMaterials.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DevD.FutureMaterials.Controllers
{
    [LogFilter]
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult Index()
        {
            IList<ProdutoModel> lista = new List<ProdutoModel>
            {
                new ProdutoModel()
                {
                    Id = 1,
                    Nome = "Tinta Azul",
                    Caracteristica = "Sustentável, smart",
                    PrecoMedio = 1000,
                    Logotipo = "Biomass",
                    Ativo = true,
                    TipoProduto = null
                },
                new ProdutoModel()
                {
                    Id = 2,
                    Nome = "Tinta Vermelha",
                    Caracteristica = "Sustentável, smart",
                    PrecoMedio = 1000,
                    Logotipo = "Biomass",
                    Ativo = true,
                    TipoProduto = null
                },
                new ProdutoModel()
                {
                    Id = 3,
                    Nome = "Tinta Rosa",
                    Caracteristica = "Sustentável",
                    PrecoMedio = 800,
                    Logotipo = "Biomass",
                    Ativo = false,
                    TipoProduto = null
                },
                new ProdutoModel()
                {
                    Id = 4,
                    Nome = "",
                    Caracteristica = "Smart",
                    PrecoMedio = 4000,
                    Logotipo = "Empresa 1",
                    Ativo = false,
                    TipoProduto = null
                },
                new ProdutoModel()
                {
                    Id = 5,
                    Nome = "",
                    Caracteristica = "Sustentável, smart",
                    PrecoMedio = 5000,
                    Logotipo = "Empresa 2",
                    Ativo = true,
                    TipoProduto = null
                }
            };
            return View(lista);
        }

        // GET: Produto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Produto/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Produto/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DevD.FutureMaterials/Views/Produto/Create.cshtml
@model DevD.FutureMaterials.Models.ProdutoModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Caracteristica" class="control-label"></label>
                <input asp-for="Caracteristica" class="form-control" />
                <span asp-validation-for="Caracteristica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoMedio" class="control-label"></label>
                <input asp-for="PrecoMedio" class="form-control" />
                <span asp-validation-for="PrecoMedio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logotipo" class="control-label"></label>
                <input asp-for="Logotipo" class="form-control" />
                <span asp-validation-for="Logotipo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="reset" value="Clear" class="btn btn-primary" />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DevD.FutureMaterials/Views/Produto/Delete.cshtml
@model DevD.FutureMaterials.Models.ProdutoModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Caracteristica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Caracteristica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecoMedio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecoMedio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logotipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logotipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DevD.FutureMaterials/Views/Produto/Details.cshtml
@model DevD.FutureMaterials.Models.ProdutoModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Caracteristica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Caracteristica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecoMedio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecoMedio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logotipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logotipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

DevD.FutureMaterials/Views/Produto/Edit.cshtml
@model DevD.FutureMaterials.Models.ProdutoModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Caracteristica" class="control-label"></label>
                <input asp-for="Caracteristica" class="form-control" />
                <span asp-validation-for="Caracteristica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoMedio" class="control-label"></label>
                <input asp-for="PrecoMedio" class="form-control" />
                <span asp-validation-for="PrecoMedio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logotipo" class="control-label"></label>
                <input asp-for="Logotipo" class="form-control" />
                <span asp-validation-for="Logotipo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="reset" value="Clear" class="btn btn-primary" />
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

DevD.FutureMaterials/Views/Produto/Index.cshtml
@model IEnumerable<DevD.FutureMaterials.Models.ProdutoModel>

@{
    ViewData["Title"] = "Produtos";
}

<h1>@ViewData["Title"]</h1>

<a asp-action="Create" asp-controller="Produto">Novo Produto</a>
<br />
<br />
<table>
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Características</th>
        <th>Preço Médio</th>
        <th>Logotipo</th>
        <th>Ativo</th>
        <th>Tipo de Produto</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <label>@item.Id</label>
            </td>
            <td>
                <label>@item.Nome</label>
            </td>
            <td>
                <label>@item.Caracteristica</label>
            </td>
            <td>
                <label>@item.PrecoMedio</label>
            </td>
            <td>
                <label>@item.Logotipo</label>
            </td>
            <td>
                <label>@item.Ativo</label>
            </td>
            <td>
                <label>@item.TipoProduto</label>
            </td>
            <td>
                <a asp-action="Details" asp-controller="Produto" asp-route-id="@item.Id">Consultar</a>
                <a asp-action="Edit" asp-controller="Produto" asp-route-id="@item.Id">Atualizar</a>
                <a asp-action="Delete" asp-controller="Produto" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
    }
</table>